development:
  graphite_url: http://graphite.danica.brachium-system.net/render/?
  graph_height: 300
  graph_width: 550
  graph_time_day: '-30h'
  graph_time_week: '-8d'
  graph_time_month: '-33d'
  graph_time_year: '400d'
  graph_colors: 00CC00 0066B3 FF8000 FFCC00 330099 990099 CCFF00 FF0000 808080 008F00 00487D B35A00 B38F00 6B006B 8FB300 B30000 BEBEBE 80FF80 80C9FF FFC080 FFE680 AA80FF EE00CC FF8080 666600 FFBFFF 00FFCC CC6699 999900
  graph_single_color: 00aa00
  graph_major_grid_line_color: efadad
  graph_minor_grid_line_color: d0d0d0
  graph_background_color: f3f3f3
  graph_foreground_color: black
  graph_fontsize: 9
  dboard_refresh_time: 61

production:
  graphite_url: http://graphite.danica.brachium-system.net/render/?
  graph_height: 300
  graph_width: 550
  graph_time_day: '-30h'
  graph_time_week: '-8d'
  graph_time_month: '-33d'
  graph_time_year: '400d'
  graph_colors: 00CC00 0066B3 FF8000 FFCC00 330099 990099 CCFF00 FF0000 808080 008F00 00487D B35A00 B38F00 6B006B 8FB300 B30000 BEBEBE 80FF80 80C9FF FFC080 FFE680 AA80FF EE00CC FF8080 666600 FFBFFF 00FFCC CC6699 999900
  graph_single_color: 00aa00
  graph_major_grid_line_color: efadad
  graph_minor_grid_line_color: d0d0d0
  graph_background_color: f3f3f3
  graph_foreground_color: black
  graph_fontsize: 9
  dboard_refresh_time: 60
